name: CI
on:
    push:
        branches:
            - master
jobs:
  build:
    name: Build2
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
    with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            pwd
        
        
